### ISSUE TITLE
Venn diagram tool for gene sets across multiple pages

### ISSUE THREAD

**Issue by jessiecheng25** [MaayanLab/covid19_crowd_library#131]
How can we compare multiple gene sets across different “pages” using the Venn diagram tool? When I select gene sets for comparison on one page and proceed to the next page to check off more, the ones from the previous page vanish.

**Comment by maxim-k** [comment]
@jeevangelista I suspect the problem is that we render tables on the server-side, so each page exists only when we see it (I kinda wanna make some cool Cartesian reference here, but I can't). I believe creating a global variable for each category and storing selected row ids in them is the least bothersome solution.
